FROM container-registry.oracle.com/os/oraclelinux:8

COPY rpms /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    rm -rfv /var/cache/yum /tmp/* /LICENSES &&\
    ln -s /usr/share/licenses /LICENSES

FROM container-registry.oracle.com/os/oraclelinux:8-slim

WORKDIR /

ADD ./images/entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
