FROM container-registry.oracle.com/os/oraclelinux:8

COPY rpms /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    rm -rfv /var/cache/yum /tmp/* /LICENSES &&\
    ln -s /usr/share/licenses /LICENSES

FROM container-registry.oracle.com/os/oraclelinux:8-slim

COPY --from=0 /LICENSES /usr/src/multus-cni/LICENSE
COPY --from=0 /usr/bin /usr/src/multus-cni/bin

COPY --from=0 /usr/bin/install_multus /
COPY --from=0 /usr/bin/thin_entrypoint /

WORKDIR /

ENTRYPOINT ["/thin_entrypoint"]
