@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}";
String image_tag = "v" + version;
String registry_namespace = "olcne";
String registry = "container-registry.oracle.com/" + registry_namespace;

olcnePipeline(
    branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: "feature/.*"),
    containers: [
        (registry + '/multus-cni:' + image_tag) : registry_namespace + '/multus-cni:' + image_tag,
    ],
    platforms: ['ol8'],
    yumOL8Repos: ['ol8_appstream', 'ol8_codeready_builder', 'ol8_addons'],
    customPlatformStages: [
      customPlatformSteps: [
        ol8: [container: [enabled: true], buildContainerRpms: [enabled: true]],
      ],
    ],
)

