@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "4.3.0";
String image_tag = "v" + version;
String registry_namespace = "olcne";
String registry = "container-registry.oracle.com/" + registry_namespace;

olcnePipeline(
    branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: "feature/.*"),
    containers: [
        (registry + '/multus-cni:' + image_tag) : registry_namespace + '/multus-cni:' + image_tag,
    ],
    platforms: ['ol8', 'ol9'],
    architectures: ['x86_64', 'aarch64'],
    yumOL8Repos: ['ol8_appstream', 'ol8_codeready_builder', 'ol8_addons'],
    yumOL9Repos: ['ol9_appstream', 'ol9_codeready_builder', 'ol9_addons'],
    customPlatformStages: [
      customPlatformSteps: [
        ol8: [container: [enabled: true], buildContainerRpms: [enabled: true]],
        ol9: [container: [enabled: false], buildContainerRpms: [enabled: false]],
      ],
    ],
)

